In [4]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data=pd.read_excel(r"C:\Users\user\Clean_Data.xlsx")

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14218 entries, 0 to 14217
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Typeofsales              14218 non-null  object
 1   Patient_ID               14218 non-null  float64
 2   Specialisation           14218 non-null  int64
 3   Dept                     14218 non-null  int64
 4   Dateofbill               14218 non-null  datetime64[ns]
 5   Quantity                 14218 non-null  float64
 6   ReturnQuantity           14218 non-null  float64
 7   Final_Cost               14218 non-null  float64
 8   Final_Sales              14218 non-null  float64
 9   RtnMRP                   14218 non-null  float64
 10  Formulation              14218 non-null  object
 11  DrugName                 14218 non-null  object
 12  SubCat                   14218 non-null  object
 13  SubCat1                  14218 non-null  object
 14  Range of Qauntity        14218 non-null  object
 15  Range of ReturnQuantity  14218 non-null  object
 16  Range of Final_Cost      14212 non-null  object
 17  Range of Final_Sales     14218 non-null  object
 18  Range of RtnMRP          14215 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(2), object(10)
memory usage: 2.1+ MB

Explolatery Data Analysis

Four Movment of Business Decision
1 : Central Tendancy(Mean,Median,Mode)
2: Measure Of Dispertion(Variance,Standard Deviation,Range)
3: Skewness(Left Skewd,Right Skewd)
4: Kurtosis(PlytoKurtosis,Mesokurtossi,Leptokurtosis)

1 : Central Tendancy

In [14]:
x=data.iloc[:,5:10]

In [17]:
x.describe()

           Quantity  ReturnQuantity    Final_Cost   Final_Sales        RtnMRP
count  14218.000000    14218.000000  14218.000000  14218.000000  14218.000000
mean      74.820977       24.843974  16618.444033  19816.626906   4011.971334
std       43.376850       14.422153   9622.537121  11360.143092   2310.030695
min        0.009071        0.003556     41.262560      1.451618      0.136496
25%       37.009179       12.212146   8257.797290  10097.007176   2021.258526
50%       74.851126       24.781048  16624.443128  19899.872413   4018.565474
75%      112.240941       37.209909  25008.331003  29610.834569   6018.058464
max      149.998210       49.993746  33176.215445  39479.744486   8013.837894

1 : Mean

In [21]:
print("The Average Value of Ratio fields Are" )
x.mean()

The Average Value of Ratio Colums is

Quantity             74.820977
ReturnQuantity       24.843974
Final_Cost        16618.444033
Final_Sales       19816.626906
RtnMRP             4011.971334
dtype: float64

2: Median

In [22]:
print("The Median Value of Ratio fields Are" )
x.median()

The Median Value of Ratio fields Are

Quantity             74.851126
ReturnQuantity       24.781048
Final_Cost        16624.443128
Final_Sales       19899.872413
RtnMRP             4018.565474
dtype: float64

In [24]:
y=data.loc[:,["Specialisation","Dept","Formulation","DrugName","SubCat","SubCat1"]]

In [27]:
print("The Most repeated Value of Category fields Are" )
y.mode()

The Most repeated Value of Category fields Are

,Specialisation,Dept,Formulation,DrugName,SubCat,SubCat1
0,29,0,Form1,SODIUM CHLORIDE IVF 100ML,INJECTIONS,INTRAVENOUS & OTHER STERILE SOLUTIONS

2: Measure Of Dispertion

In [32]:
print("This are the varience of Field of Ratio")
x.var()

This are the varience of Field of Ratio

Quantity          1.881551e+03
ReturnQuantity    2.079985e+02
Final_Cost        9.259322e+07
Final_Sales       1.290529e+08
RtnMRP            5.336242e+06
dtype: float64

In [33]:
print("The Standard Deviation of Ratio field")
x.std()

The Standard Deviation of Ratio field

Quantity             43.376850
ReturnQuantity       14.422153
Final_Cost         9622.537121
Final_Sales       11360.143092
RtnMRP             2310.030695
dtype: float64

In [34]:
print("The Range of Ratio field")
x.max()-x.min()

Quantity            149.989138
ReturnQuantity       49.990190
Final_Cost        33134.952885
Final_Sales       39478.292868
RtnMRP             8013.701398
dtype: float64

3: Skewness

In [35]:
print("The skewd data of ratio field")
x.skew()

Quantity         -0.001067
ReturnQuantity    0.015823
Final_Cost       -0.009373
Final_Sales      -0.017295
RtnMRP           -0.001903
dtype: float64

4: Kurtosis

In [ ]:
print("The kurtosis data of ratio field")
x.kurt()